# This file is part of pg2pandas.
# https://github.com/belonesox/pg2pandas

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2018, Stas Fomin <stas-fomin@yandex.ru>

language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
